// GENERATED FILE - do not edit. Regenerate with:  php misc/gen-js-constants.php
// TypeScript twin of modules/burglebros.constants.js - same enums, same warnings:
// the values are load-bearing on the client and in the DB of running games,
// never rename them here or in PHP.
export const BBCONST = {
    // NotifType (modules/NotifType.class.php)
    NOTIF: {
        Message: "message",
        ActivatePlayer: "activatePlayer",
        AddTooltipToLog: "addTooltipToLog",
        CatEscaped: "catEscaped",
        CatPicked: "catPicked",
        CharacterChosen: "characterChosen",
        CreateGuardPath: "createGuardPath",
        DecrementStealth: "decrementStealth",
        DiceRolled: "diceRolled",
        EventCard: "eventCard",
        NextPatrol: "nextPatrol",
        PatrolDieIncreased: "patrolDieIncreased",
        PlayerEscape: "playerEscape",
        PlayerHand: "playerHand",
        RemoveWall: "removeWall",
        SafeDieIncreased: "safeDieIncreased",
        ShowFloor: "showFloor",
        TileCards: "tileCards",
        TileFlipped: "tileFlipped",
        TokensPicked: "tokensPicked",
        TokensPickedSync: "tokensPickedSync",
        UpdateGuardPath: "updateGuardPath",
        UpdateWalls: "updateWalls",
    },
    // CardType (modules/CardType.class.php)
    CARD_TYPE: {
        Character: 0,
        Tool: 1,
        Loot: 2,
        Event: 3,
        Patrol1: 4,
        Patrol2: 5,
        Patrol3: 6,
    },
    // TileType (modules/TileType.class.php)
    TILE_TYPE: {
        Atrium: "atrium",
        Camera: "camera",
        FingerprintComputer: "fingerprint-computer",
        LaserComputer: "laser-computer",
        MotionComputer: "motion-computer",
        Deadbolt: "deadbolt",
        Detector: "detector",
        Fingerprint: "fingerprint",
        Foyer: "foyer",
        Keypad: "keypad",
        Laboratory: "laboratory",
        Laser: "laser",
        Lavatory: "lavatory",
        Motion: "motion",
        Safe: "safe",
        SecretDoor: "secret-door",
        ServiceDuct: "service-duct",
        Stairs: "stairs",
        Thermo: "thermo",
        Walkway: "walkway",
        Shaft: "shaft",
        Back: "back",
    },
    // TokenType (modules/TokenType.class.php)
    TOKEN_TYPE: {
        Guard: "guard",
        Patrol: "patrol",
        Player: "player",
        Crack: "crack",
        Hack: "hack",
        Safe: "safe",
        Stealth: "stealth",
        Alarm: "alarm",
        Open: "open",
        Keypad: "keypad",
        Stairs: "stairs",
        Thermal: "thermal",
        Crowbar: "crowbar",
        Crow: "crow",
        Cat: "cat",
        Die: "die",
    },
    // DeckType (modules/DeckType.class.php)
    DECK_TYPE: {
        Characters: "characters",
        Tools: "tools",
        Loot: "loot",
        Events: "events",
        Patrol1: "patrol1",
        Patrol2: "patrol2",
        Patrol3: "patrol3",
    },
} as const;
